services:
# Redis
  redis:
    image: redis:latest
    container_name: rd-redis
    command: redis-server --dir /data
    restart: always
    volumes:
    - ./docker-data/redis:/data
    ports:
    - 6379:6379
  # Mongo
  mongo:
    hostname: mongo
    image: mongo
    container_name: rd-mongo
    restart: always
    volumes:
    - ./app/mongo:/var/lib/mongodb
    expose:
      - 27017
    ports:
    - 27017:27017
    command: mongod --port 27017