services:
# Redis
  redis:
    image: redis:latest
    container_name: rd-redis
    command: redis-server --dir /data
    restart: always
    volumes:
    - ./docker-data/redis:/data
    ports:
    - "127.0.0.1:6379:6379" # 绑定到 localhost
  # Mongo
  mongo:
    hostname: mongo
    image: mongo
    container_name: rd-mongo
    restart: always
    volumes:
    - ./docker-data/mongo:/var/lib/mongodb
    expose:
      - 27017
    ports:
    - "127.0.0.1:27017:27017" # 绑定到 localhost
    command: mongod --port 27017